### ISSUE TITLE
Spherical Cow / SL2S Paper V model

### ISSUE THREAD

**Issue by astrosonnen** [astrosonnen/allZeLenses#7]
I generated an SL2S-IV-like sample of time-delay lenses and fitted it with the same model used to generate the mock.
The inference on H0 is biased. The issue might be due to the way I sample over the individual systems and/or the way I calculate the integrals over the individual lens parameters.

- [x] Check that conditional PDF is not being truncated somehow when sampling the individual systems - solution could be to re-parameterize
- [x] Simplify the problem until the bias goes away, then gradually increase complexity again to identify the bug.
- [x] Document this experiment in a notebook (complete with PGM #12)

**Comment by drphilmarshall** [comment]
Maybe there is some interim/conditional PDF truncation going on? I feel like that could be an issue...

**Comment by astrosonnen** [comment]
I think I narrowed down the origin of the problem. The bias starts occurring when sampling over the source position. If I use the same set of mock lenses and I do the inference fitting only the Einstein radii instead of the image positions, the bug disappears.
Now why does the marginalization over the source position introduce a bias in the mean dark matter mass?

**Comment by astrosonnen** [comment]
By the way, the conditional PDF of the individual systems is being truncated, but the probability distribution in the individual parameters given the hyper-parameters is renormalized accordingly during the hierarchical inference, so it is not an issue.

**Comment by drphilmarshall** [comment]
​Are you solving the lens equation to predict image positions, or tracing
back image positions to estimate the source position? The latter is known
to introduce a bias, even if you trace back the image position
uncertainties via the magnification matrix​ as well.

**Comment by astrosonnen** [comment]
I am solving the lens equation. The source position is another free 
parameter of the model. I am assuming a flat prior in the square of the 
distance from the optical axis (so that it is uniform in 2d), the 
same used to generate the mock, and then I marginalize over the source 
position when doing the hierarchical inference.

**Comment by astrosonnen** [comment]
Let's do this. Let's keep the model with the bug for the moment, and let's use it to do our first posterior predictive check with it.
Presumably it will fail, maybe we can learn something more from it.

**Comment by drphilmarshall** [comment]
Good plan. We can compare models that predict the data well, with models
that are close to the truth.

Your comparison with the no-source-parameters model seems to show that the
priors for our other model parameters are OK. Maybe the issue is the joint
PDF for the source position and (at least) one other parameter. Is that
parameter the density profile slope?

**Comment by astrosonnen** [comment]
I think I've found the issue. The prior on the source position should be flat between the center and the radial caustic. The caustic changes with the model parameters, so the prior must be updated as well. If I do that, things seem to finally work...

**Comment by drphilmarshall** [comment]
I guess this prior follows from the assumption "the object is a strong
lens" - but its interesting that it has to be applied so rigorously! Which
way did the bias go, do you know? Was it due to truncating the source
position, or allowing it to range too widely? In any case - well caught!

**Comment by astrosonnen** [comment]
I think I was allowing for too large values of the source position.
It makes little to no difference on the individual lens, but in the 
hierarchical inference it gave a 2-sigma bias on the dark matter mass 
(and therefore on the density slope and the cosmology).

**Comment by drphilmarshall** [comment]
While we work on the [second checkbox of this epic above](https://github.com/astrosonnen/allZeLenses/issues/7#issue-58015435), we also need a notebook to keep track of it. That should be the move we make right after we agree on the PGM we are talking about.

**Comment by astrosonnen** [comment]
The inference appears to be accurate now, as it should. All bugs found so far are documented [here](https://github.com/astrosonnen/allZeLenses/blob/master/notebooks/Failed_Experiments.ipynb)

**Comment by drphilmarshall** [comment]
Excellent! I see the notebook that is linked to above only contains the "problem formulation", though - I think this notebook should be named after the model we have defined, and have a results section as well as a PGM section. Show us the corner plots! :-)
